window:
  title: System
system:
  distance_threshold: 2.0
  count_threshold:
    - 1
    - 2
    - 3
  warning_color:
    - green
    - yellow
    - red
excel:
  worksheet_name: NLink_LinkTrack_Node_Frame1
chart:
  title: 距离折线图
  y_axis: 距离
  x_axis: 索引